openapi: "3.0.2"
info:
  title: "AMP T2D Property registry API"
  description: "Property registry API for the project AMP-T2D"
  version: "1.0SNAPSHOT"
  termsOfService: "www.ebi.ac.uk/terms"
  contact:
    name: "Property registry API Admin"
    url: "www.ebi.ac.uk"
    email: "prop@gmail.com"
  license:  
    name: "Apache 2.0"
    url: "https://www.apache.org/license/"
servers:
  - url: https://www.ebi.ac.uk/ega/ampt2d/propertyreg/1.0/
    description: Production server
paths:
  /phenotypes:
    get:
      tags:
      - Phenotype Entity
      summary: "find all phenotypes."
      description: "Get all phenotypes of Type2Diabetes."
      operationId: GetPhenotypeEntity
      parameters:
      - name: page
        in: query
        description: "Number of pages."
        schema:
          type: string
      - name: size
        in: query
        description: "size of page."
        schema:
          type: string
      - name: sort
        in: query
        description: "Ascending or descending."
        schema:
          type: string
      responses:
        200:
          description: OK, Successful response
          content:
            application/json:
              schema:
                title: Model
                type: object
                properties:
                  id:
                    type: string
                    description: generated id of phenotype
                  phenotypeGroup:
                    type: string
                    enum: [ANTHROPOMETRIC,CARDIOVASCULAR,GLYCEMIC]
                    description: phenotype group
                  description:
                    type: string
                    description: description of phenotype
                  type:
                    type: string
                    enum: [DICHOTOMOUS, MULTICHOTOMOUS]
                    description: description of phenotype
                  allowedValues:
                    type: string
                    description: allowed values of phenotype                      
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not found
    post:
      tags:
      - Phenotype Entity
      summary: "save phenotype."
      description: "Store a phenotype of Type2Diabetes."
      operationId: PostPhenotypeEntity
      requestBody:
        description: Store a phenotype of Type2Diabetes.
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Phenotype'
        required: true
      responses:
        200:
          description: OK, Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  links:
                    type: array
                    items:
                      type: object
                      properties:
                        href:
                          type: string
                        rel:
                          type: string
                        templated:
                          type: boolean
                  id:
                    type: string
                  phenotypeGroup:
                    type: string
                    enum: [ANTHROPOMETRIC,CARDIOVASCULAR,GLYCEMIC]
                  description:
                    type: string
                  type:
                    type: string
                    enum: [DICHOTOMOUS, MULTICHOTOMOUS]
                  allowedValues:
                    type: string
        201:
          description: Created
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not found
          
components:
  schemas:
    Phenotype:
      type: object
      properties:
        id:
          type: string
          description: generated id of phenotype
        phenotypeGroup:
          type: string
          enum: [ANTHROPOMETRIC,CARDIOVASCULAR,GLYCEMIC]
          description: phenotype group
        description:
          type: string
          description: description of phenotype
        type:
          type: string
          enum: [DICHOTOMOUS, MULTICHOTOMOUS]
          description: description of phenotype
        allowedValues:
          type: string
          description: allowed values of phenotype   
      xml:
        name: Phenotype
  securitySchemes:
    keycloak_auth:
      type: oauth2
      flows:
        authorizationCode:
          tokenUrl:  http://localhost:8080/ega/ampt2d/auth/realms/securemetadata/protocol/openid-connect/token
          authorizationUrl: http://localhost:8080/ega/ampt2d/auth/realms/securemetadata/protocol/openid-connect/auth
          scopes:
            opened: openid
